name: vizeo_theme
description: Vizeo Theme
version: 0.2
publish_to: 'none'
homepage: https://github.com/VIZEODEV/eu_vizeo_flutter_vizeotheme

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get:

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  lint:


flutter:
  fonts:
    - family: Icons_App
      fonts:
        - asset: assets/fonts/Icons_App.ttf
    - family: DIN2014
      fonts:
        - asset: assets/fonts/DIN2014-Regular.ttf
          weight: 500
        - asset: assets/fonts/DIN2014-Bold.ttf
          weight: 700
        - asset: assets/fonts/DIN2014-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/DIN2014-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DIN2014-Light.ttf
          weight: 300
        - asset: assets/fonts/DIN2014-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DIN2014-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DIN2014-DemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/DIN2014-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/DIN2014-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/DIN2014-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/DIN2014-ExtraLightItalic.ttf
          weight: 200
          style: italic